export const implementedPublicRoutes = [
  '/',
  '/about',
  '/product',
  '/how-it-works',
  '/privacy',
  '/data-ownership',
  '/users',
  '/researchers',
  '/partners',
  '/investors',
  '/demo',
  '/waitlist',
  '/faq',
  '/terms',
  '/updates',
  '/contact',
  '/content',
  '/stories',
  '/rituals',
  '/narrator',
  '/voice-packs',
  '/marketplace',
  '/creator',
  '/pricing',
  '/licensing',
  '/exports',
  '/roadmap',
  '/versions'
] as const;

export type ImplementedPublicRoute = (typeof implementedPublicRoutes)[number];
